# Generated by Django 5.0.4 on 2024-05-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start1_app', '0002_alter_recipes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='recipe_images'),
        ),
    ]
