# Generated by Django 5.0.4 on 2024-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start1_app', '0003_alter_recipes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecategorylink',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipecategorylink',
            name='recipe',
            field=models.ManyToManyField(related_name='in_order', to='start1_app.recipes'),
        ),
    ]
